 site_name: My work experience # Название сайта
 site_description: My work experience in last projects # Описание сайта, добавляется в meta-теги
 nav: # Структура сайта
    - Readme: index.md
    - Projects: 
      - Проект 1: index_1.md
      - Проект 2: index_2.md
      - Проект 3: index_3.md
 copyright:
  (c) AVENTIS 2026
  
 theme:  # Тема сайта, информация о ее параметрах
   name: material  # Название темы
   palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal 
      accent: amber  
      toggle:
       icon: material/brightness-7
       name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber 
      toggle:
       icon: material/brightness-4
       name: Switch to light mode
   logo: logo.jpg  # Ссылка на логотип сайта
   font:
    text: Inter  # Шрифт текста
    code: Fira Code  # Шрифт для текста кода
   features:  # Функции темы
    - navigation.sections  # Настройка секций навигации
    - navigation.path  # Хлебные крошки
    - navigation.indexes  # Позволяет создавать корневые страницы разделов меню.
    - navigation.tabs  # Верхнее меню
    - navigation.tabs.sticky  # Фиксация верхнего меню
    - navigation.expand  # Разворачивает спойлеры в левом меню по умолчанию
    - toc.integrate  # Фиксирует оглавление страницы в левом меню
    #- navigation.instant  # Функция быстрой загрузки страниц
    - navigation.top  # Добавляет кнопку «к началу» для быстрой обратной прокрутки страницы
    - search.suggest  # Подсказки при вводе поискового запроса
    - search.highlight  # Подсветка результатов поиска в тексте страницы
    - content.code.copy  # Кнопка копирования в блоке кода
    - content.code.annotate   # аннотации в блоках кода (стрелочки с пояснениями)
    - content.tabs.link       # синхронизация вкладок между собой
    - content.tooltips        # всплывающие подсказки при наведении
    - header.autohide         # шапка скрывается при прокрутке вниз
    - navigation.prune        # не грузит все страницы в меню (быстрее работает)
    - announce.dismiss       # баннер можно закрыть
   language: ru # Язык
   
 