openapi: 3.0.3
info:
  title: Objects API
  version: 1.0.0
paths:
  /objects:
    get:
      summary: Получить список объектов
      responses:
        '200':
          description: Список объектов успешно получен
    post:
      summary: Создать объект
      responses:
        '201':
          description: Объект успешно создан